# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'TopTapBar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TopTapBar
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'SnapKit'
  pod 'XLPagerTabStrip', '~> 9.0'
end
